// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Store_link.Data.Context;

#nullable disable

namespace Online_Store_link.Migrations
{
    [DbContext(typeof(OnlineStoreContext))]
    [Migration("20220627173953_v6")]
    partial class v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Online_Store_link.Models.DBModels.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("f1025ff3-4bda-4b04-bee8-91c7b58b68a6"),
                            ArabicName = "بلاي ستايشن",
                            Description = "playStation 5 plack color come with 2 hadles",
                            Name = "PlayStation",
                            Price = 2200.5m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductID = new Guid("2be8a360-aa1b-4dd5-b591-6c412d123432"),
                            ArabicName = "بلاي ستايشن",
                            Description = "playStation 5 plack color come with 2 hadles",
                            Name = "Mobile",
                            Price = 2200.5m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductID = new Guid("cd6a8469-d0dd-4915-acc9-a6d6dfacf019"),
                            ArabicName = "بلاي ستايشن",
                            Description = "playStation 5 plack color come with 2 hadles",
                            Name = "IPhone",
                            Price = 2200.5m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductID = new Guid("509c4617-d463-4d59-85b8-d27c851e5a9e"),
                            ArabicName = "بلاي ستايشن",
                            Description = "playStation 5 plack color come with 2 hadles",
                            Name = "Tablet",
                            Price = 2200.5m,
                            Quantity = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
